syntax = "proto3";

option go_package = "github.com/PlakarKorp/go-secret-sdk;sdk";

package secret_provider;

service SecretProvider {
  rpc Init(InitRequest) returns (InitResponse);
  rpc Resolve(ResolveRequest) returns (ResolveResponse);
  rpc Close(CloseRequest) returns (CloseResponse);
}

message InitRequest {
  map<string, string> config = 1;
}

message InitResponse {}

message ResolveRequest {
  string handle = 1;
}

message ResolveResponse {
  string secret = 1;
}

message CloseRequest  {}
message CloseResponse {}
